SET IDENTITY_INSERT [dbo].[Desarrollador] ON
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (1, N'Bungie', N'
Bungie Studios és una empresa dissenyadora de videojocs fundada en 1991 sota el nom de Bungie Programari Productes Corporation per dos estudiants de la Universitat de Chicago, Alex Seropian i Jason Jones. Forma part dels estudis de videojocs de Microsoft des que aquesta empresa la va comprar en l''any 2000
            ', N'Estados Unidos', N'2023-05-18', N'www.gogole.com', N'~/Imagenes/ss.png')
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (4, N'Cuellilargos', N'Cuellilargos es un error de la naturaleza', N'Estados Unidosasdasdasd', N'2023-05-18', N'www.counter-strike.net', N'~/Imagenes/jeje.png')
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (6, N'Rana24', N'Descripcion de ejemeplo 23', N'Rumania', N'2023-05-18', N'www.counter-strike.net', N'~/Imagenes/catcat.jpg')
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (7, N'Desarrolador 56', N'Arkane Studios SASU es una compañía francesa desarrolladora de videojuegos con sede en Lyon, Francia. Fue fundada en 1999 por once personas, entre estas Raphaël Colantonio y seis desarrolladores. Arkane studios abrió una subsidiaria en Austin, Texas con cargos listos en julio de 2006', N'Francia', N'2023-05-18', N'www.counter-strike.net', N'~/Imagenes/ofifinc.jpg')
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (8, N'eeeeeeeeeeeeee', N'
Bungie Stuewdasdasdasdasddios és una empresa dissenyadora de videojocs fundada en 1991 sota el nom de Bungie Programari Productes Corporation per dos estudiants de la Universitat de Chicago, Alex Seropian i Jason Jones. Forma part dels estudis de videojocs de Microsoft des que aquesta empresa la va comprar en l''any 2000
            ', N'adsadsdsadasdadsadsd', N'2023-05-18', N'www.counter-strike.net', N'~/Imagenes/gustav.png')
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (9, N'chinochino', N'es japones asdasd', N'pais cosa', N'2023-05-18', N'Label.com', N'~/Imagenes/cebolla.jpg')
INSERT INTO [dbo].[Desarrollador] ([id], [nombre], [descripcion], [origen], [fecha_creacion], [web], [imagen]) VALUES (10, N'Nombre de cosa', N'lorem ipsum', N'orgen?', N'2023-05-18', N'www.google.com', N'~/Imagenes/mandariner.jpg')
SET IDENTITY_INSERT [dbo].[Desarrollador] OFF
