-- Rellenar CategoriaProducto
insert into CategoriaProducto values('cat1', 'desc1', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat2', 'desc2', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat3', 'desc3', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat4', 'desc4', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat5', 'desc5', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat6', 'desc6', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat7', 'desc7', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat8', 'desc8', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat9', 'desc9', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat10', 'desc10', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat11', 'desc11', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat12', 'desc12', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat13', 'desc13', '~/Imagenes/sinimagen.jpeg')
insert into CategoriaProducto values('cat14', 'desc14', '~/Imagenes/sinimagen.jpeg')